parameters:
#    esiee_game.example.class: ESIEE\GameBundle\Example

services:
    game.form.type.tiletype:
        class: ESIEE\GameBundle\Form\Type\TileType
        tags:
            - { name: form.type, alias: tiletype }

    game.form.type.tileselector:
        class: ESIEE\GameBundle\Form\Type\TileSelectorType
        tags:
            - { name: form.type, alias: tileselector }

    sonata.admin.ground:
        class: ESIEE\GameBundle\Admin\GroundAdmin
        arguments:
            - ~
            - ESIEE\GameBundle\Entity\Ground
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Elements de jeu", label: Terrains }


    sonata.admin.unittype:
        class: ESIEE\GameBundle\Admin\UnitTypeAdmin
        arguments:
            - ~
            - ESIEE\GameBundle\Entity\UnitType
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Elements de jeu", label: "Types d'unité" }


    sonata.admin.unitspeed:
        class: ESIEE\GameBundle\Admin\UnitSpeedAdmin
        arguments:
            - ~
            - ESIEE\GameBundle\Entity\UnitSpeed
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Elements de jeu", label: "Coût de déplacement" }


    sonata.admin.unit:
        class: ESIEE\GameBundle\Admin\UnitAdmin
        arguments:
            - ~
            - ESIEE\GameBundle\Entity\Unit
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Elements de jeu", label: "Unités" }


    sonata.admin.tilefamily:
        class: ESIEE\GameBundle\Admin\TileFamilyAdmin
        arguments:
            - ~
            - ESIEE\GameBundle\Entity\TileFamily
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Elements de jeu", label: "Familles de tiles" }


    sonata.admin.tile:
        class: ESIEE\GameBundle\Admin\TileAdmin
        arguments:
            - ~
            - ESIEE\GameBundle\Entity\Tile
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Elements de jeu", label: "Tiles" }
