esiee_editor:
    resource: "@ESIEEEditorBundle/Resources/config/routing.yml"
    prefix:   /editor

esiee_game:
    resource: "@ESIEEGameBundle/Resources/config/routing.yml"
    prefix:   /play

esiee_user:
    resource: "@ESIEEUserBundle/Resources/config/routing.yml"
    prefix:   /users

home:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::home.html.twig'

login_check:
    path: /login_check

logout:
    path: /logout

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

#sonata_user_resetting:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
#    prefix: /resetting
#
#sonata_user_profile:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
#    prefix: /profile
#
#sonata_user_register:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
#    prefix: /register
#
#sonata_user_change_password:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
#    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin