parameters:
#    esiee_editor.example.class: ESIEE\EditorBundle\Example

services:
#    esiee_editor.example:
#        class: %esiee_editor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
