<?php

namespace ESIEE\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * BuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->createQueryBuilder('b')
            ->select('b.id, b.name, b.coordX x, b.coordY y')
            ->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}
