<?php

namespace ESIEE\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ESIEE\UserBundle\Entity\User;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findForUser(User $user)
    {
        return $this->createQueryBuilder('g')
            ->where('g.creator = :user OR g.opponent = :user')
            ->setParameter('user', $user)
            ->getQuery()->getResult();
    }
}
