<?php

namespace ESIEE\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use ESIEE\GameBundle\Entity\Game;
use ESIEE\UserBundle\Entity\User;

/**
 * JsMsgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JsMsgRepository extends EntityRepository
{
    public function findMsg(Game $game = null, User $user = null)
    {
        $result = $this->createQueryBuilder('m')
            ->where('m.game = :game')
            ->setParameter('game', $game)
            ->andWhere('m.for = :user')
            ->setParameter('user', $user)
            ->setMaxResults(1)
            ->getQuery()->getResult(Query::HYDRATE_ARRAY);

        return count($result) == 1 ? $result[0] : null;
    }

    public function removeMsg($msg)
    {
        $this->createQueryBuilder('m')
            ->delete()
            ->where('m.id = :id')
            ->setParameter('id', $msg['id'])
            ->getQuery()->execute();
    }
}
