<?php

namespace ESIEE\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * TileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TileRepository extends EntityRepository
{
    public function findAllSimple()
    {
        return $this->createQueryBuilder('t')
            ->select('t.id, t.type, t.distribution, t.coordX x, t.coordY y, IDENTITY(t.tileFamily) family')
            ->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}
