<?php

namespace ESIEE\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * TileFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TileFamilyRepository extends EntityRepository
{
    public function findAllSimple()
    {
        return $this->createQueryBuilder('f')
            ->select('f.id, f.name, IDENTITY(f.ground) ground')
            ->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}
