<?php

namespace ESIEE\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TileRepository extends EntityRepository
{
}
