<?php

namespace ESIEE\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TileFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TileFamilyRepository extends EntityRepository
{
}
