<?php

namespace ESIEE\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends EntityRepository
{
    public function findAllSimple()
    {
        return $this->createQueryBuilder('u')
            ->select('u.id, u.name, u.description , u.longDescription longDesc, u.power, u.range, u.defence defense')
            ->addSelect('u.fast, u.attackFirst defender, u.assassin assassin, t.name moveType, u.movement moveValue')
            ->addSelect('u.coordX x, u.coordY y')
            ->leftJoin('u.unitType', 't')
            ->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}
